language: ruby
cache: bundler

rvm:
  - 2.1
  - 2.2

env:
  - DB=sqlite
  - DB=mysql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database owma-api_test'
